#!/bin/bash

if [ $# -ne 2 ]; then
	echo -e "Usage:\n$0 input_file output_file"
	exit 1
fi
python preprocess.py $1 .tempimg.bmp
convert .tempimg.bmp -colors 256 -type Palette -compress None .tempimg256.bmp
rdmd bmptoasm.d .tempimg256.bmp >.tempimg256.asx
xasm /q ivb2.asx /o:$2
